=== rafajlpz/DAM-Lenguajes/Tareas/UD4/403/403repaso.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="impresoras">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="impresora" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fabricante" type="xs:string"></xs:element>
                            <xs:element name="modelo" type="xs:string"></xs:element>
                            <xs:element name="peso">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minExclusive value="0" />
                                        <xs:fractionDigits value="2" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tamaño" type="xs:string" maxOccurs="unbounded">
                            </xs:element>
                            <xs:element name="cartucho">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="C-[0-9]{3}[A-Z]{1,2}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="enred" type="xs:string" minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="numSerie" type="xs:ID" use="required"></xs:attribute>
                        <xs:attribute name="tecnologia" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="matricial"></xs:enumeration>
                                    <xs:enumeration value="láser"></xs:enumeration>
                                    <xs:enumeration value="tinta"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="compra" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minExclusive value="0"></xs:minExclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rafajlpz/DAM-Lenguajes/Tareas/UD4/403/403repaso.xml
<?xml version="1.0" encoding="UTF-8"?>
<impresoras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="403repaso.xsd">
    <impresora numSerie="i245" tecnologia="láser" compra="2010">
        <fabricante>Epson</fabricante>
        <modelo>EPL300</modelo>
        <peso>4.52</peso>
        <tamaño>A4</tamaño>
        <tamaño>A5</tamaño>
        <cartucho>C-123BV</cartucho>
        <enred />
    </impresora>
    <impresora numSerie="i246" tecnologia="matricial">
        <fabricante>HP</fabricante>
        <modelo>LaserJet 2410</modelo>
        <peso>3.2</peso>
        <tamaño>A4</tamaño>
        <cartucho>C-456P</cartucho>
    </impresora>
</impresoras>
