=== rafajlpz/DAM-Lenguajes/Tareas/UD4/404/404.xsd
<!-- Declaracion XSD -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Elemento raiz -->
    <xs:element name="tienda">
        <!-- Tipo de dato complejo al tener varios elementos -->
        <xs:complexType>
            <!-- Secuencia del orden productos, clientes, ventas -->
            <xs:sequence>
                <!-- Elemento productos -->
                <xs:element name="productos" minOccurs="1" maxOccurs="unbounded">
                    <!-- Tipo de dato complejo al tener varios elementos y atributos -->
                    <xs:complexType>
                        <!-- Secuencia del orden producto -->
                        <xs:sequence>
                            <!-- Elemento producto -->
                            <xs:element name="producto" minOccurs="1" maxOccurs="unbounded">
                                <!-- Tipo de dato complejo al tener varios elementos y atributos -->
                                <xs:complexType>
                                    <!-- Secuencia del orden de elementos -->
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"></xs:element>
                                        <xs:element name="fabricante" type="xs:string"></xs:element>
                                        <xs:element name="modelo" type="xs:string"></xs:element>
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="divisa" type="xs:string"
                                                            use="required" />
                                                        <xs:attribute name="descuento"
                                                            type="xs:decimal" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                            <!--  -->

                                        </xs:element>
                                        <xs:element name="stock" type="xs:positiveInteger"></xs:element>
                                        <xs:element name="reacondicionado" minOccurs="0" />
                                    </xs:sequence>
                                    <xs:attribute name="idP" type="xs:string" use="required" />
                                    <xs:attribute name="ean" type="xs:string" />
                                    <xs:attribute name="iva" type="xs:decimal" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="clientes" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="apellidos" type="xs:string"></xs:element>
                                        <xs:element name="dni"></xs:element>
                                        <xs:element name="telefono" minOccurs="0"
                                            maxOccurs="unbounded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\+\d{2} \d{9}" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="direccion" type="xs:string" minOccurs="0" />
                                    </xs:sequence>
                                    <xs:attribute name="idC" type="xs:string" use="required" />
                                    <xs:attribute name="creado" type="xs:date" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ventas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="venta" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="item" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="ref" type="xs:string"
                                                    use="required" />
                                                <xs:attribute name="cantidad"
                                                    type="xs:positiveInteger" use="optional" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="total">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="divisa" type="xs:string"
                                                            use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="fecha" type="xs:date" use="required" />
                                    <xs:attribute name="hora" type="xs:time" use="required" />
                                    <xs:attribute name="cliente" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


            </xs:sequence>


        </xs:complexType>

    </xs:element>
</xs:schema>

=== rafajlpz/DAM-Lenguajes/Tareas/UD4/404/404.xml
<?xml version="1.0" encoding="UTF-8"?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="404.xsd">
    <productos>
        <producto idP="P1" ean="5397063521906" iva="21">
            <titulo>Portátil Dell XPS 15</titulo>
            <fabricante>Dell</fabricante>
            <modelo>XPS 15</modelo>
            <precio divisa="EUR">1000.00</precio>
            <stock>20</stock>
            <reacondicionado />
        </producto>
        <producto idP="P2" iva="21">
            <titulo>Tablet Samsung Galaxy Tab S7</titulo>
            <fabricante>Samsung</fabricante>
            <modelo>Galaxy Tab S7</modelo>
            <precio divisa="EUR">700.00</precio>
            <stock>15</stock>
        </producto>
        <producto idP="P3" ean="0889894812605" iva="21">
            <titulo>Impresora HP OfficeJet Pro 7740</titulo>
            <fabricante>HP</fabricante>
            <modelo>OfficeJet Pro 7740</modelo>
            <precio divisa="USD" descuento="10">150.00</precio>
            <stock>10</stock>
        </producto>
    </productos>
    <clientes>
        <cliente idC="C1" creado="2022-12-25">
            <nombre>Antonio</nombre>
            <apellidos>Pérez Martínez</apellidos>
            <dni>12345678A</dni>
            <telefono>+34 666555444</telefono>
            <direccion>Avenida de Romero Donallo, 13</direccion>
        </cliente>
        <cliente idC="C2" creado="2022-12-12">
            <nombre>María</nombre>
            <apellidos>García Pérez</apellidos>
            <dni>87654321B</dni>
            <telefono>+34 755444333</telefono>
            <telefono>+34 655444333</telefono>
            <direccion>Calle Santiago de Chile, 45</direccion>
        </cliente>
        <cliente idC="C3" creado="2022-01-03">
            <nombre>Mario</nombre>
            <apellidos>Martínez López</apellidos>
            <dni>38343578A</dni>
        </cliente>
    </clientes>
    <ventas>
        <venta fecha="2023-01-09" hora="18:01:25" cliente="C2">
            <item ref="P3" cantidad="8" />
            <item ref="P2" />
            <total divisa="EUR">1900.00</total>
        </venta>
        <venta fecha="2023-01-21" hora="09:54:07" cliente="C1">
            <item ref="P1" />
            <item ref="P2" />
            <total divisa="EUR">1700.00</total>
        </venta>
    </ventas>
</tienda>
