=== rafajlpz/DAM-Lenguajes/Tareas/UD4/402/402repaso.dtd
<!-- Designamos el elemento raiz y lo que contiene -->
<!ELEMENT tienda (productos, clientes, ventas)>
<!-- Designamos el elemento productos, que contiene uno o varios producto -->
<!ELEMENT productos (producto+)>
<!-- Designamos el elemento producto y los elementos que contiene -->
<!ELEMENT producto (titulo, (fabricante|marca), modelo, precio, stock, reacondicionado?)>
<!-- Atributos de producto -->
<!ATTLIST producto idP ID #REQUIRED>
<!ATTLIST producto ean CDATA #IMPLIED>
<!ATTLIST producto iva (general|reducido|superreducido) #REQUIRED>
<!-- Elementos de producto -->
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fabricante (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!-- Atributos de precio -->
<!ATTLIST precio divisa (EUR|USD) #REQUIRED>
<!ATTLIST precio descuento CDATA "0">
<!-- Elementos de producto -->
<!ELEMENT stock (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT reacondicionado EMPTY>

<!-- Designamos el elemento clientes, que contiene uno, ninguno o varios clientes -->
<!ELEMENT clientes (cliente*)>
<!-- Designamos el elemento cliente y los elementos que contiene -->
<!ELEMENT cliente (((nombre, apellidos) | nombre-completo), dni, telefono*, direccion?)>
<!-- Atributos de cliente -->
<!ATTLIST cliente idC ID #REQUIRED>
<!ATTLIST cliente creado CDATA #REQUIRED>
<!-- Elementos de cliente -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT nombre-completo (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>


<!-- Designamos el elemento ventas, que contiene uno, ninguna o varias ventas -->
<!ELEMENT ventas (venta*)>
<!-- Designamos el elemento venta y los elementos que contiene -->
<!ELEMENT venta (item+, total)>
<!-- Atributos de venta -->
<!ATTLIST venta fecha CDATA #REQUIRED>
<!ATTLIST venta cliente IDREF #REQUIRED>
<!-- Elemento de cliente -->
<!ELEMENT item EMPTY>
<!-- Atributos de item -->
<!ATTLIST item ref IDREF #REQUIRED>
<!ATTLIST item cantidad CDATA "1">
<!-- Elemento de cliente -->
<!ELEMENT total (#PCDATA)>
<!-- Atributos de total -->
<!ATTLIST total divisa (EUR|USD) #REQUIRED>

=== rafajlpz/DAM-Lenguajes/Tareas/UD4/402/402repaso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "402repaso.dtd">
<tienda>
    <productos>
        <producto idP="P1" ean="5397063521906" iva="general">
            <titulo>Portátil Dell XPS 15</titulo>
            <fabricante>Dell</fabricante>
            <modelo>XPS 15</modelo>
            <precio divisa="EUR">1000</precio>
            <stock>20</stock>
            <reacondicionado />
        </producto>
        <producto idP="P2" iva="general">
            <titulo>Tablet Samsung Galaxy Tab S7</titulo>
            <marca>Samsung</marca>
            <modelo>Galaxy Tab S7</modelo>
            <precio divisa="EUR">700</precio>
            <stock>15</stock>
        </producto>
        <producto idP="P3" ean="0889894812605" iva="general">
            <titulo>Impresora HP OfficeJet Pro 7740</titulo>
            <fabricante>HP</fabricante>
            <modelo>OfficeJet Pro 7740</modelo>
            <precio divisa="EUR" descuento="10">150</precio>
            <stock>10</stock>
        </producto>
    </productos>
    <clientes>
        <cliente idC="C1" creado="25-12-2022">
            <nombre>Antonio</nombre>
            <apellidos>Pérez Martínez</apellidos>
            <dni>12345678A</dni>
            <telefono>666555444</telefono>
            <direccion>Avenida de Romero Donallo, 13</direccion>
        </cliente>
        <cliente idC="C2" creado="12-12-2022">
            <nombre-completo>María García Pérez</nombre-completo>
            <dni>87654321B</dni>
            <telefono>755444333</telefono>
            <telefono>655444333</telefono>
            <direccion>Calle Santiago de Chile, 45</direccion>
        </cliente>
        <cliente idC="C3" creado="03-01-2022">
            <nombre>Mario</nombre>
            <apellidos>Martínez López</apellidos>
            <dni>318343578A</dni>
        </cliente>
    </clientes>
    <ventas>
        <venta fecha="09-01-2023" cliente="C2">
            <item ref="P3" cantidad="8" />
            <item ref="P2" />
            <total divisa="EUR">1900</total>
        </venta>
        <venta fecha="21-01-2023" cliente="C1">
            <item ref="P1" />
            <item ref="P2" />
            <total divisa="EUR">1700</total>
        </venta>
    </ventas>
</tienda>
